services:
    frontend:
        build: .
        env_file:
            -   .env
        ports:
            - '3000:3000'
        environment:
            ZEROBOUNCE_API_KEY: ${ZEROBOUNCE_API_KEY}
            API_SERVICE: ${API_SERVICE}
            MAIL_SERVICE: ${MAIL_SERVICE}
